# Generated by Django 5.2.17 on 2026-08-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Akad Nikah / Resepsi', max_length=60)),
                ('waktu_mulai', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('nama_tempat', models.CharField(max_length=160)),
                ('alamat', models.TextField(blank=True)),
                ('url_maps', models.URLField(blank=True, help_text='Link Google Maps lokasi acara.')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Acara',
                'verbose_name_plural': 'Acara',
                'ordering': ['urutan', 'waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('keterangan', models.CharField(blank=True, max_length=160)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto Galeri',
                'verbose_name_plural': 'Foto Galeri',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pengantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(choices=[('pria', 'Mempelai Pria'), ('wanita', 'Mempelai Wanita')], max_length=10, unique=True)),
                ('nama_lengkap', models.CharField(max_length=120)),
                ('nama_panggilan', models.CharField(max_length=60)),
                ('anak_ke', models.CharField(blank=True, help_text='Contoh: Putra pertama', max_length=40)),
                ('nama_ayah', models.CharField(blank=True, max_length=120)),
                ('nama_ibu', models.CharField(blank=True, max_length=120)),
                ('instagram', models.CharField(blank=True, help_text='Tanpa tanda @', max_length=60)),
                ('foto', models.ImageField(blank=True, upload_to='pengantin/')),
            ],
            options={
                'verbose_name': 'Mempelai',
                'verbose_name_plural': 'Mempelai',
                'ordering': ['peran'],
            },
        ),
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Undangan Pernikahan', max_length=120)),
                ('hashtag', models.CharField(blank=True, help_text='Contoh: #RinaDanBudi', max_length=60)),
                ('quote', models.TextField(blank=True, help_text='Kutipan / ayat yang tampil di layar pembuka.')),
                ('sumber_quote', models.CharField(blank=True, max_length=120)),
                ('musik', models.FileField(blank=True, help_text='Lagu latar (.mp3). Diputar setelah tamu menekan tombol Buka Undangan.', upload_to='musik/')),
                ('catatan_penutup', models.TextField(blank=True, default='Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu.')),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
            },
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(help_text='Contoh: BCA, Mandiri, GoPay', max_length=60)),
                ('nomor', models.CharField(max_length=60)),
                ('atas_nama', models.CharField(max_length=120)),
                ('qr', models.ImageField(blank=True, help_text='Opsional: gambar QRIS.', upload_to='qr/')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rekening Hadiah',
                'verbose_name_plural': 'Rekening Hadiah',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('sapaan', models.CharField(blank=True, help_text='Contoh: Bapak, Ibu, Saudara/i.', max_length=40)),
                ('jumlah_undangan', models.PositiveIntegerField(default=1)),
                ('catatan', models.CharField(blank=True, max_length=200)),
                ('pertama_dibuka', models.DateTimeField(blank=True, null=True)),
                ('jumlah_dibuka', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tamu',
                'verbose_name_plural': 'Daftar Tamu',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Ucapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('pesan', models.TextField()),
                ('kehadiran', models.CharField(choices=[('hadir', 'Insya Allah hadir'), ('tidak', 'Maaf, tidak dapat hadir'), ('ragu', 'Masih ragu')], default='hadir', max_length=10)),
                ('jumlah_orang', models.PositiveIntegerField(default=1)),
                ('disetujui', models.BooleanField(default=True, help_text='Hilangkan centang untuk menyembunyikan dari papan ucapan.')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('tamu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ucapan', to='undangan.tamu')),
            ],
            options={
                'verbose_name': 'Ucapan & RSVP',
                'verbose_name_plural': 'Ucapan & RSVP',
                'ordering': ['-dibuat'],
            },
        ),
    ]
