# Generated by Django 5.2.17 on 2026-08-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturan',
            name='tema',
            field=models.CharField(choices=[('klasik', 'Taman Pixel - tampak atas'), ('tropis', 'Taman Tropis - isometrik')], default='klasik', help_text='Tampilan undangan. Tema lain bisa dicoba lewat parameter tema pada URL.', max_length=20),
        ),
    ]
