# Generated by Django 4.2.30 on 2026-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undangan', '0003_alter_pengaturan_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturan',
            name='tema',
            field=models.CharField(choices=[('klasik', 'Taman Pixel Jawa - tampak atas'), ('tropis', 'Taman Tropis - isometrik'), ('lombok', 'Pantai Lombok Sasak Wedding'), ('desa', 'Desa Asri Parahyangan - Gaya Stardew Valley'), ('gedung', 'Grand Ballroom Gedung Mewah - Modern Indoor-Outdoor')], default='klasik', help_text='Tampilan undangan. Tema lain bisa dicoba lewat parameter tema pada URL.', max_length=20),
        ),
    ]
