# Generated by Django 4.2.30 on 2026-09-07 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undangan', '0005_alter_pengaturan_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotogaleri',
            name='gambar_url',
            field=models.CharField(blank=True, help_text='Tautan gambar eksternal (Google Drive, Imgur, Cloudinary, dll).', max_length=500),
        ),
        migrations.AddField(
            model_name='pengantin',
            name='foto_url',
            field=models.CharField(blank=True, help_text='Atau tempel tautan gambar eksternal (Google Drive, Imgur, Web URL).', max_length=500),
        ),
        migrations.AddField(
            model_name='rekening',
            name='qr_url',
            field=models.CharField(blank=True, help_text='Atau tempel tautan gambar QRIS.', max_length=500),
        ),
        migrations.AlterField(
            model_name='fotogaleri',
            name='gambar',
            field=models.ImageField(blank=True, upload_to='galeri/'),
        ),
        migrations.AlterField(
            model_name='pengantin',
            name='peran',
            field=models.CharField(choices=[('pria', 'Mempelai Pria'), ('wanita', 'Mempelai Wanita')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rekening',
            name='qr',
            field=models.ImageField(blank=True, help_text='Opsional: unggah gambar QRIS.', upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.CreateModel(
            name='Undangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Tautan unik undangan. Contoh: budi-dan-ani -> domain.com/u/budi-dan-ani', max_length=120, unique=True)),
                ('judul', models.CharField(default='Undangan Pernikahan', max_length=120)),
                ('tema', models.CharField(choices=[('klasik', 'Taman Pixel Jawa - tampak atas'), ('tropis', 'Taman Tropis - isometrik'), ('lombok', 'Pantai Lombok Sasak Wedding'), ('desa', 'Desa Asri Parahyangan - Gaya Stardew Valley'), ('gedung', 'Grand Ballroom Gedung Mewah - Modern Indoor-Outdoor'), ('safari', 'Taman Safari Kebun Binatang Rimba Tropis')], default='klasik', help_text='Pilihan tema visual game interaktif.', max_length=20)),
                ('hashtag', models.CharField(blank=True, help_text='Contoh: #BudiAniWedding', max_length=60)),
                ('quote', models.TextField(blank=True, help_text='Kutipan ayat / kata mutiara di layar awal.')),
                ('sumber_quote', models.CharField(blank=True, help_text='Contoh: QS. Ar-Rum: 21', max_length=120)),
                ('musik', models.FileField(blank=True, help_text='Unggah file musik (.mp3 / .wav).', upload_to='musik/')),
                ('musik_url', models.CharField(blank=True, help_text='Atau tempel link file audio eksternal jika tidak ingin upload berkas.', max_length=500)),
                ('catatan_penutup', models.TextField(blank=True, default='Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu.')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_undangan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Undangan',
                'verbose_name_plural': 'Daftar Undangan',
                'ordering': ['-dibuat'],
            },
        ),
        migrations.AddField(
            model_name='acara',
            name='undangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acara_list', to='undangan.undangan'),
        ),
        migrations.AddField(
            model_name='fotogaleri',
            name='undangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galeri_list', to='undangan.undangan'),
        ),
        migrations.AddField(
            model_name='pengantin',
            name='undangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mempelai_list', to='undangan.undangan'),
        ),
        migrations.AddField(
            model_name='rekening',
            name='undangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rekening_list', to='undangan.undangan'),
        ),
        migrations.AddField(
            model_name='tamu',
            name='undangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tamu_list', to='undangan.undangan'),
        ),
        migrations.AddField(
            model_name='ucapan',
            name='undangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucapan_list', to='undangan.undangan'),
        ),
    ]
