# Generated by Django 4.2.30 on 2026-09-07 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undangan', '0006_fotogaleri_gambar_url_pengantin_foto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='undangan',
            name='aktif_berakhir',
            field=models.DateTimeField(blank=True, help_text='Batas waktu online aktif berbayar (30 hari).', null=True),
        ),
        migrations.AddField(
            model_name='undangan',
            name='status_langganan',
            field=models.CharField(choices=[('trial', 'Masa Uji Coba (1 Jam)'), ('menunggu', 'Menunggu Konfirmasi Pembayaran'), ('aktif', 'Aktif Penuh (Berbayar)'), ('kadaluarsa', 'Masa Aktif Habis')], default='trial', help_text='Status keaktifan & masa berlangganan undangan.', max_length=20),
        ),
        migrations.AddField(
            model_name='undangan',
            name='trial_berakhir',
            field=models.DateTimeField(blank=True, help_text='Batas waktu uji coba gratis 1 jam sejak dibuat.', null=True),
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.PositiveIntegerField(default=30000, help_text='Biaya aktivasi Rp 30.000 / bulan.')),
                ('durasi_bulan', models.PositiveIntegerField(default=1)),
                ('metode', models.CharField(default='Transfer Bank / QRIS', max_length=60)),
                ('bukti_bayar', models.ImageField(upload_to='bukti_bayar/')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('disetujui', 'Disetujui / Aktif'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('catatan', models.TextField(blank=True, help_text='Catatan transfer dari user / alasan penolakan.')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diverifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('undangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pembayaran', to='undangan.undangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_pembayaran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Daftar Pembayaran',
                'ordering': ['-dibuat'],
            },
        ),
    ]
