# Generated by Django 4.2.30 on 2026-09-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undangan', '0007_undangan_aktif_berakhir_undangan_status_langganan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undangan',
            name='aktif_berakhir',
            field=models.DateTimeField(blank=True, help_text='Batas waktu online aktif berbayar (30 hari / fleksibel).', null=True),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='status_langganan',
            field=models.CharField(choices=[('trial', 'Masa Uji Coba (1 Hari)'), ('menunggu', 'Menunggu Konfirmasi Pembayaran'), ('aktif', 'Aktif Penuh (Berbayar)'), ('kadaluarsa', 'Masa Aktif Habis')], default='trial', help_text='Status keaktifan & masa berlangganan undangan.', max_length=20),
        ),
        migrations.AlterField(
            model_name='undangan',
            name='trial_berakhir',
            field=models.DateTimeField(blank=True, help_text='Batas waktu uji coba gratis 1 hari sejak dibuat.', null=True),
        ),
    ]
