# Generated by Django 5.2.17 on 2026-10-07 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undangan', '0009_trial_1_bulan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfigurasiAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama pengenal, contoh: Claude via 9Router', max_length=80)),
                ('provider', models.CharField(choices=[('9router', '9Router (Router AI Lokal / OpenAI-Compatible)'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('custom', 'Kustom (OpenAI-Compatible: Ollama, LM Studio, dll)')], default='9router', max_length=20)),
                ('base_url', models.CharField(blank=True, help_text='Kosongkan untuk memakai alamat bawaan provider.', max_length=300)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('model', models.CharField(help_text='Nama model AI, contoh: claude-sonnet-4-5', max_length=150)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('timeout_detik', models.PositiveIntegerField(default=120)),
                ('kirim_pdf_langsung', models.BooleanField(default=True, help_text='Kirim berkas PDF utuh ke AI (agar desain/gambar ikut terbaca) bila provider mendukung.')),
                ('is_aktif', models.BooleanField(default=False, help_text='Konfigurasi yang dipakai aplikasi.')),
                ('status_tes', models.CharField(choices=[('belum', 'Belum Dites'), ('berhasil', 'Berhasil'), ('gagal', 'Gagal')], default='belum', max_length=10)),
                ('pesan_tes', models.TextField(blank=True)),
                ('latensi_tes_ms', models.PositiveIntegerField(default=0)),
                ('terakhir_dites', models.DateTimeField(blank=True, null=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi AI',
                'verbose_name_plural': 'Konfigurasi AI',
                'ordering': ['-is_aktif', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='ai_aktif',
            field=models.BooleanField(default=True, help_text='Izinkan pengguna membuat undangan otomatis dari PDF menggunakan AI.'),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='ai_batas_harian',
            field=models.PositiveIntegerField(default=5, help_text='Batas jumlah analisis PDF yang berhasil per pengguna per hari (0 = tanpa batas).'),
        ),
        migrations.AddField(
            model_name='pengaturan',
            name='ai_khusus_berbayar',
            field=models.BooleanField(default=False, help_text='Jika dicentang, fitur AI hanya tersedia untuk undangan yang sudah aktif berbayar.'),
        ),
        migrations.CreateModel(
            name='RiwayatAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('ukuran_kb', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('mode_baca', models.CharField(blank=True, help_text="'pdf' = PDF dikirim utuh, 'teks' = hanya teks hasil ekstraksi.", max_length=10)),
                ('jumlah_karakter_teks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('sukses', 'Berhasil Dianalisis'), ('gagal', 'Gagal'), ('diterapkan', 'Sudah Diterapkan ke Undangan')], default='sukses', max_length=12)),
                ('hasil', models.JSONField(blank=True, default=dict)),
                ('pesan_error', models.TextField(blank=True)),
                ('durasi_ms', models.PositiveIntegerField(default=0)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diterapkan_pada', models.DateTimeField(blank=True, null=True)),
                ('konfigurasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat', to='undangan.konfigurasiai')),
                ('undangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_ai', to='undangan.undangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_ai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat AI',
                'verbose_name_plural': 'Riwayat AI',
                'ordering': ['-dibuat'],
            },
        ),
    ]
